# Generated by Django 4.0.5 on 2022-08-09 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeStamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_dt', models.DateField(auto_now=True)),
                ('edit_dt', models.DateField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='tweet',
            old_name='Img',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='tweet',
            old_name='Owner',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='Edit_dt',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='Text',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='Upload_dt',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='id',
        ),
        migrations.AddField(
            model_name='tweet',
            name='text',
            field=models.CharField(default=1, max_length=2048),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tweet',
            name='timestamp_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='postapp.timestamp'),
            preserve_default=False,
        ),
    ]
