# Generated by Django 4.0.5 on 2022-06-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Date_Of_Birth',
            field=models.DateField(null=True),
        ),
    ]
