# Generated by Django 4.0.5 on 2022-08-09 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0003_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Profile',
            field=models.FileField(upload_to='Profile/'),
        ),
    ]
